### ISSUE TITLE
Not possible to use with Rails 7

### ISSUE THREAD

**Issue by morgoth** [geekq/workflow-activerecord#12]
The Rails 7 RC1 is out.
It would be nice to be able test and use this gem with it.
https://weblog.rubyonrails.org/2021/12/6/Rails-7-0-rc-1-released/

**Comment by elsurudo** [comment]
Yes, this would be great, as rails 7.0.0 is out as of December 15th.

**Comment by geekq** [comment]
Have you guys already tried it out? What does work / does not work?

Background: though I've adjusted the gemspec to trigger the CI build, I can not quickly try it out.
Unfortunately after the acquisition Travis CI stopped working for open source projects 6 month ago
(last builds can be seen here: https://app.travis-ci.com/github/geekq/workflow-activerecord/builds)

First I would need to switch to some new CI like in
https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

If somebody provides a pull request for adding GitHub Actions, I would be happy to merge it. Otherwise you'll need to wait a bit more.

**Comment by geekq** [comment]
Update: got it, the rails version was limited in the gemspec:
https://github.com/geekq/workflow-activerecord/blob/develop/workflow_activerecord.gemspec#L26

Just removed that restriction, you can try it out installing from source as described in https://bundler.io/guides/git.html Please let me know, if you've experienced any incompatibilities with Rails 7 or not.

I'll repackage and release the gem *after* switching to a new CI - can take a while.

**Comment by elsurudo** [comment]
Thanks for making the tweak. FYI I ran it against my app's test suite (rails 7.0.0) and no issues detected so far (I exercise the state machine in the specs, but nothing exhaustive). If I notice anything, I'll post here.

**Comment by morgoth** [comment]
@geekq The version from master with Rails 7 also works fine within my app.

**Comment by geekq** [comment]
Thanks @morgoth for https://github.com/geekq/workflow-activerecord/pull/13 ! :heart: 
Just released the workflow-activerecord 4.1.9 https://rubygems.org/gems/workflow-activerecord/versions/4.1.9

**Comment by morgoth** [comment]
Thanks
