### ISSUE TITLE
uninitialized constant WorkflowActiverecord (NameError)

### ISSUE THREAD

**Issue by stefanahman** [geekq/workflow-activerecord#3]
Hello,

I'm getting `uninitialized constant WorkflowActiverecord (NameError)` unless I require the workflow libs at the top of the file: 
```ruby
require 'workflow'
require 'workflow_activerecord'
```

Is this a part of the design or have I missed something?

Using version: `workflow-activerecord (4.1.2)`

Thanks!

**Comment by geekq** [comment]
Hi Stefan,

yes, this is the way it currently works and is demonstrated in the sample application
https://github.com/geekq/workflow-rails-sample/blob/master/app/models/article.rb#L1-L4

Thank you for asking - I'll look for a way to make this 2 requires unnessesary.
Need to dive deeper into Rails initializers and/or autoloading:
https://guides.rubyonrails.org/autoloading_and_reloading_constants.html

Looks like some gems eliminate the need for require and some do not:
Compare to https://stackoverflow.com/questions/30797488/require-a-gem-in-rails

**Comment by rockorequin** [comment]
The problem is to do with naming - the gemfile uses a hyphen, whereas the file to require uses an underscore to separate out workflow and activerecord. 

ie in the Gemfile, we have:

gem 'workflow-activerecord'

and so bundler tries to require 'workflow-activerecord' instead of 'workflow_activerecord'.

**Comment by geekq** [comment]
@rockorequin Thanks for debugging the behaviour of different bundler versions!

Could you please post a link to the bundler documentation and/or implementation, which describes the gem + require behaviour?

P.S. I've also found you original comment helpful:

> Is this something to do with bundler? I think bundler is the one that automatically requires all gems in the Gemfile (eg see https://www.justinweiss.com/articles/how-does-rails-handle-gems/).
>
> Using ruby 2.6.2 with its default bundler 1.17.2, Rails 5.0.2, and the workflow_activerecord 4.1.2 / workflow 2.0 gems, I almost got the same problem as the OP: I didn't have to require 'workflow', but I did have to require 'workflow_activerecord'.
>
> However, after upgrading to bundler 2 (https://bundler.io/guides/bundler_2_upgrade.html) I no longer have to require either 'workflow' or 'workflow_activerecord'. On the other hand, I now have to include Workflow as well as include WorkflowActiverecord, or I get the exception 'method workflow not defined'. It's all very confusing!

**Comment by geekq** [comment]
The fashion in the Rails and the Ruby community - more magic require or more explicit require - changes over time.

Here is an overview and some arguments pro explicitness (which I also endorse): https://anti-pattern.com/use-bundler-setup-instead-of-bundler-require.

**Comment by rockorequin** [comment]
> @rockorequin Thanks for debugging the behaviour of different bundler versions!

> 
> P.S. I've also found you original comment helpful:
> 
> > Is this something to do with bundler?...

No problem! Glad to help. But I actually deleted my original comment because the third paragraph was incorrect and I didn't want to include misleading information. (When I re-tested it, I found I _did_ have to require workflow_activity and I _didn't_ have to include record, so I now think the different versions of Bundler work exactly the same.)
  
> 
> Could you please post a link to the bundler documentation and/or implementation, which describes the gem + require behaviour?

I found this guide for naming: https://guides.rubygems.org/name-your-gem/

It's not quite what you asked for, but I thought it might be of interest because it recommends that a gem named "a-b" should be required with "require 'a/b'" whereas a gem named "a_b" should be required with "require 'a_b'". 

I think that means that we should either do:

```
Gemfile: gem "workflow_activerecord"
Require: require "workflow_activerecord"

```

or

```
Gemfile: gem "workflow-activerecord"
Require: require "workflow/activerecord"
```

In the first case, Bundler will issue the "require 'workflow_activerecord'" automatically. However, I don't think that second example matches what Bundler.require actually does - based on what I found, it just executes a "require '<name of gem>' statement, whether the gem has a hyphen in it or not.

**Comment by svoop** [comment]
I get things to work (on Bundler 2) by including `WorkflowActiverecord` and explicitly requesting "require" in the Gemfile for both workflow and workflow-activerecord:

```ruby
gem 'workflow', require: 'workflow'
gem 'workflow-activerecord', '>= 4.1', '< 6.0', require: 'workflow_activerecord'
```

**Comment by rockorequin** [comment]
@svoop: Thanks, that's a nice solution. It works for me too if I specify the require in the Gemfile, but I only need it for workflow-activerecord:

```
gem 'workflow', '~> 2.0'
gem 'workflow-activerecord', '>=4.1', '<6.0', require: 'workflow_activerecord'

```

**Comment by geekq** [comment]
It looks, that both dashes and underscores in gem name are widely spread in Ruby community. Eric Hodel (developer of rubygems) explains when he recommends which
<https://web.archive.org/web/20090525085426/http://blog.segment7.net/articles/2009/05/20/a-project-naming-recommendation> So in case of workflow-activerecord the dash is even the right one (symbolizing the extension of workflow).

The only problem - the naming of **the source code** files does not match the convention https://guides.rubygems.org/name-your-gem/

If we move `lib/workflow_activerecord.rb` to `lib/workflow/activerecord.rb` and rename the class to `Workflow::ActiveRecord`, all the magic should work. I will try out after Easter...
